[package]
name = "day_4"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex-literal = "0.4.1"
# md5 = "0.7.0"
md-5 = "0.10.5"
